import globals from "globals";
import jsdoc from "eslint-plugin-jsdoc";
import react from "eslint-plugin-react";
import stylistic from "@stylistic/eslint-plugin";
import typescript from "@typescript-eslint/eslint-plugin";

import typescriptParser from "@typescript-eslint/parser"

const SOURCE_DIR = "src";
const RULES = getRules();

export default [
    {
        ignores: [
            `${SOURCE_DIR}/presentation/components/primitives/rn-reusables/**/*`,
            `${SOURCE_DIR}/presentation/utils/cn.util.ts`,
            `${SOURCE_DIR}/presentation/hooks/rn-reusables/**/*`,
        ],
    },
    {
        files: [`${SOURCE_DIR}/**/*.{jsx,tsx}`, "./App.{jsx,tsx}"],
        languageOptions: {
            parser: typescriptParser,
            globals: {
                ...globals.node,
                ...globals.es2022,
            },
            ecmaVersion: 2022,
            parserOptions: {
                ecmaVersion: 2022,
                sourceType: "module",
                project: "./tsconfig.json",
                ecmaFeatures: {
                    jsx: true,
                },
            },
        },
        plugins: { jsdoc, react, stylistic, typescript },
        rules: {
            ...getFlattenedRules("eslint", "jsdoc", "react", "stylistic", "typescript"),
            "typescript/naming-convention": [
                "warn",
                {
                    selector: "default",
                    format: ["camelCase", "PascalCase"],
                },
                {
                    selector: "variable",
                    format: ["camelCase", "UPPER_CASE"],
                },
                {
                    selector: "parameter",
                    format: ["camelCase", "PascalCase"],
                    leadingUnderscore: "forbid",
                },
                {
                    selector: "memberLike",
                    modifiers: ["private"],
                    format: ["camelCase"],
                    leadingUnderscore: "forbid",
                },
                {
                    selector: "typeLike",
                    format: ["PascalCase"],
                },
                {
                    selector: "enumMember",
                    format: ["UPPER_CASE"],
                },
                {
                    selector: "import",
                    format: ["camelCase", "PascalCase"],
                },
            ],
        }
    },
    {
        files: [`${SOURCE_DIR}/**/*.{js,ts}`],
        languageOptions: {
            parser: typescriptParser,
            globals: {
                ...globals.node,
                ...globals.es2022,
            },
            parserOptions: {
                ecmaVersion: 2022,
                sourceType: "module",
                project: "./tsconfig.json",
            },
        },
        plugins: { jsdoc, stylistic, typescript },
        rules: getFlattenedRules("eslint", "jsdoc", "stylistic", "typescript"),
    },
];

/**
 * Get rules by their scopes.
 * @param scope {string} The scope name of the rules object.
 * @returns {{}|*}
 */
function getFlattenedRules(...scope) {
    return scope.map(n => Object.hasOwn(RULES, n) ? RULES[n] : {}).reduce((acc, curr) => ({ ...acc, ...curr }), {});
}

/**
 * Get the rules object containing all ESLint rules.
 * @returns Rules object.
 */
function getRules() {
    return {
        eslint: {
            "accessor-pairs": "error",
            "array-callback-return": "error",
            "arrow-body-style": ["warn", "as-needed"],
            "block-scoped-var": "error",
            "camelcase": "warn",
            "capitalized-comments": ["warn", "always"],
            "class-methods-use-this": "off", // typescript/class-methods-use-this is set to "off".
            "complexity": ["warn", 10],
            "consistent-return": "off", // tsconfig.json has noImplicitReturns set to true.
            "consistent-this": ["warn", "self"],
            "constructor-super": "error",
            "curly": "warn",
            "default-case": "error",
            "default-case-last": "error",
            "default-param-last": "off", // typescript/default-param-last is set to "error".
            "dot-notation": "off", // typescript/dot-notation is set to "error".
            "eqeqeq": ["error", "smart"],
            "for-direction": "error",
            "func-name-matching": "warn",
            "func-names": ["warn", "always"],
            "func-style": ["warn", "declaration", { "allowArrowFunctions": true }],
            "getter-return": "warn",
            "grouped-accessor-pairs": ["warn", "getBeforeSet"],
            "guard-for-in": "error",
            "id-denylist": "off",
            "id-length": "off",
            "id-match": "off",
            "init-declarations": "off", // typescript/init-declarations is set to "off".
            "logical-assignment-operators": "off",
            "max-classes-per-file": ["warn", 1],
            "max-depth": ["warn", 4],
            "max-lines": ["warn", { "max": 256, "skipBlankLines": true, "skipComments": true }],
            "max-lines-per-function": ["warn", { "max": 128, "skipBlankLines": true, "skipComments": true }],
            "max-nested-callbacks": ["warn", 3],
            "max-params": "off", // typescript/max-params is set to "warn".
            "max-statements": "off",
            "new-cap": "off",
            "no-alert": "error",
            "no-array-constructor": "off", // typescript/no-array-constructor is set to "error".
            "no-async-promise-executor": "error",
            "no-await-in-loop": "warn",
            "no-bitwise": "off",
            "no-caller": "error",
            "no-case-declarations": "error",
            "no-class-assign": "error",
            "no-compare-neg-zero": "warn",
            "no-cond-assign": "warn",
            "no-console": "warn",
            "no-const-assign": "error",
            "no-constant-binary-expression": "warn",
            "no-constructor-return": "error",
            "no-continue": "off",
            "no-control-regex": "off",
            "no-debugger": "error",
            "no-delete-var": "error",
            "no-div-regex": "warn",
            "no-dupe-args": "error",
            "no-dupe-class-members": "off", // typescript/no-dupe-class-members is set to "error".
            "no-dupe-else-if": "warn",
            "no-dupe-keys": "warn",
            "no-duplicate-case": "warn",
            "no-duplicate-imports": "warn",
            "no-else-return": "warn",
            "no-empty": ["warn", { "allowEmptyCatch": true }],
            "no-empty-character-class": "warn",
            "no-empty-function": "off", // typescript/no-empty-function is set to "error".
            "no-empty-pattern": "off",
            "no-empty-static-block": "warn",
            "no-eq-null": "off",
            "no-eval": "error",
            "no-ex-assign": "error",
            "no-extend-native": "error",
            "no-extra-bind": "warn",
            "no-extra-boolean-cast": "warn",
            "no-extra-label": "warn",
            "no-fallthrough": "error",
            "no-func-assign": "error",
            "no-global-assign": "error",
            "no-implicit-coercion": "warn",
            "no-implicit-globals": "off",
            "no-implied-eval": "error",
            "no-import-assign": "error",
            "no-inline-comments": "off",
            "no-inner-declarations": "error",
            "no-invalid-regexp": "error",
            "no-invalid-this": "off", // typescript/no-invalid-this is set to "error".
            "no-irregular-whitespace": "warn",
            "no-iterator": "error",
            "no-label-var": "warn",
            "no-labels": ["warn", { "allowLoop": true, "allowSwitch": true }],
            "no-lone-blocks": "warn",
            "no-lonely-if": "warn",
            "no-loop-func": "off", // typescript/no-loop-func is set to "error".
            "no-loss-of-precision": "off", // typescript/no-loss-of-precision is set to "warn".
            "no-magic-numbers": "off", // typescript/no-magic-numbers is set to "off".
            "no-misleading-character-class": "warn",
            "no-multi-assign": "warn",
            "no-multi-str": "off",
            "no-negated-condition": "warn",
            "no-nested-ternary": "warn",
            "no-new": "error",
            "no-new-func": "error",
            "no-new-native-nonconstructor": "error",
            "no-new-wrappers": "error",
            "no-nonoctal-decimal-escape": "off",
            "no-object-constructor": "warn",
            "no-octal": "warn",
            "no-octal-escape": "warn",
            "no-param-reassign": ["warn", { "props": true }],
            "no-plusplus": "off",
            "no-promise-executor-return": "error",
            "no-proto": "error",
            "no-prototype-builtins": "error",
            "no-redeclare": "off", // typescript/no-redeclare is set to "error".
            "no-regex-spaces": "warn",
            "no-restricted-exports": "off",
            "no-restricted-globals": "off",
            "no-restricted-imports": "off", // typescript/no-restricted-imports is set to "off".
            "no-restricted-properties": "off",
            "no-restricted-syntax": "off",
            "no-return-assign": ["warn", "always"],
            "no-script-url": "error",
            "no-self-assign": "warn",
            "no-self-compare": "warn",
            "no-setter-return": "off",
            "no-sequences": "warn",
            "no-shadow": "off", // typescript/no-shadow is set to "error".
            "no-shadow-restricted-names": "error",
            "no-sparse-arrays": "error",
            "no-template-curly-in-string": "warn",
            "no-ternary": "off",
            "no-this-before-super": "error",
            "no-throw-literal": "off", // typescript/only-throw-error is set to "error".
            "no-undef": "error",
            "no-undef-init": "warn",
            "no-undefined": "off",
            "no-underscore-dangle": "warn",
            "no-unexpected-multiline": "error",
            "no-unmodified-loop-condition": "error",
            "no-unneeded-ternary": ["warn", { "defaultAssignment": false }],
            "no-unreachable": "error",
            "no-unreachable-loop": "error",
            "no-unsafe-finally": "error",
            "no-unsafe-negation": "warn",
            "no-unsafe-optional-chaining": "error",
            "no-unused-expressions": "off", // typescript/no-unused-expressions is set to "warn".
            "no-unused-labels": "warn",
            "no-unused-private-class-members": "warn",
            "no-unused-vars": "off", // typescript/no-unused-vars is set to "warn".
            "no-use-before-define": "off", // typescript/no-use-before-define is set to "error".
            "no-useless-assignment": "off", // typescript/no-unused-vars is set to "error".
            "no-useless-backreference": "error",
            "no-useless-call": "warn",
            "no-useless-catch": "warn",
            "no-useless-computed-key": "warn",
            "no-useless-concat": "warn",
            "no-useless-constructor": "off", // typescript/no-useless-constructor is set to "error".
            "no-useless-escape": "off",
            "no-useless-rename": "warn",
            "no-useless-return": "warn",
            "no-var": "error",
            "no-void": "off",
            "no-warning-comments": ["warn", { "terms": ["todo", "fixme"], "location": "anywhere" }],
            "no-with": "error",
            "object-shorthand": ["warn", "always"],
            "one-var": "off",
            "operator-assignment": ["warn", "always"],
            "prefer-arrow-callback": ["warn", { "allowNamedFunctions": true }],
            "prefer-const": ["warn", { "destructuring": "all" }],
            "prefer-exponentiation-operator": "warn",
            "prefer-named-capture-group": "warn",
            "prefer-numeric-literals": "warn",
            "prefer-object-has-own": "warn",
            "prefer-object-spread": "warn",
            "prefer-promise-reject-errors": "off", // typescript/prefer-promise-reject-errors is set to "error".
            "prefer-regex-literals": "warn",
            "prefer-rest-params": "warn",
            "prefer-spread": "warn",
            "prefer-template": "warn",
            "radix": "off",
            "require-await": "off", // typescript/require-await is set to "error".
            "require-atomic-updates": "error",
            "require-unicode-regexp": "warn",
            "require-yield": "error",
            "sort-imports": ["off", { "ignoreCase": true }],
            "sort-keys": "off",
            "strict": ["warn", "safe"],
            "symbol-description": "warn",
            "use-isnan": "error",
            "valid-typeof": "error",
            "vars-on-top": "warn",
            "yoda": ["warn", "never"],
        },
        jsdoc: {
            "jsdoc/check-access": "warn",
            "jsdoc/check-alignment": "warn",
            "jsdoc/check-examples": "off",
            "jsdoc/check-indentation": "warn",
            "jsdoc/check-line-alignment": "warn",
            "jsdoc/check-param-names": "warn",
            "jsdoc/check-property-names": "warn",
            "jsdoc/check-syntax": "off",
            "jsdoc/check-tag-names": "warn",
            "jsdoc/check-template-names": "off",
            "jsdoc/check-types": "warn",
            "jsdoc/check-values": "warn",
            "jsdoc/convert-to-jsdoc-comments": "off",
            "jsdoc/empty-tags": "warn",
            "jsdoc/implements-on-classes": "warn",
            "jsdoc/informative-docs": "off",
            "jsdoc/lines-before-block": "off",
            "jsdoc/match-name": "off",
            "jsdoc/match-description": "off",
            "jsdoc/multiline-blocks": "warn",
            "jsdoc/no-bad-blocks": "off",
            "jsdoc/no-blank-block-descriptions": "off",
            "jsdoc/no-defaults": "off",
            "jsdoc/no-missing-syntax": "off",
            "jsdoc/no-multi-asterisks": "warn",
            "jsdoc/no-restricted-syntax": "off",
            "jsdoc/no-types": "warn",
            "jsdoc/no-undefined-types": "off",
            "jsdoc/require-asterisk-prefix": "off",
            "jsdoc/require-description": "warn",
            "jsdoc/require-description-complete-sentence": "off",
            "jsdoc/require-example": "off",
            "jsdoc/require-file-overview": "off",
            "jsdoc/require-hyphen-before-param-description": "warn",
            "jsdoc/require-jsdoc": "warn",
            "jsdoc/require-param": "warn",
            "jsdoc/require-param-description": "warn",
            "jsdoc/require-param-name": "warn",
            "jsdoc/require-param-type": "off",
            "jsdoc/require-property": "off",
            "jsdoc/require-property-description": "warn",
            "jsdoc/require-property-name": "warn",
            "jsdoc/require-property-type": "off",
            "jsdoc/require-returns": "warn",
            "jsdoc/require-returns-check": "warn",
            "jsdoc/require-returns-description": "warn",
            "jsdoc/require-returns-type": "off",
            "jsdoc/require-template": "off",
            "jsdoc/require-throws": "warn",
            "jsdoc/require-yields": "warn",
            "jsdoc/require-yields-check": "warn",
            "jsdoc/sort-tags": "warn",
            "jsdoc/tag-lines": "warn",
            "jsdoc/text-escaping": "off",
            "jsdoc/valid-types": "warn",
        },
        react: {
            "react/boolean-prop-naming": "warn",
            "react/button-has-type": "off",
            "react/checked-requires-onchange-or-readonly": "error",
            "react/default-props-match-prop-types": "error",
            "react/destructuring-assignment": "warn",
            "react/display-name": "off",
            "react/forbid-component-props": ["warn", { forbid: ["style"] }],
            "react/forbid-dom-props": "warn",
            "react/forbid-elements": "warn",
            "react/forbid-foreign-prop-types": "warn",
            "react/forbid-prop-types": "off",
            "react/function-component-definition": "warn",
            "react/hook-use-state": "warn",
            "react/iframe-missing-sandbox": "error",
            "react/jsx-boolean-value": "warn",
            "react/jsx-child-element-spacing": "warn",
            "react/jsx-closing-bracket-location": "warn",
            "react/jsx-closing-tag-location": "warn",
            "react/jsx-curly-brace-presence": "warn",
            "react/jsx-curly-newline": "warn",
            "react/jsx-first-prop-new-line": "warn",
            "react/jsx-fragments": "warn",
            "react/jsx-handler-names": "warn",
            "react/jsx-indent": "warn",
            "react/jsx-indent-props": "warn",
            "react/jsx-key": "error",
            "react/jsx-max-depth": "warn",
            "react/jsx-max-props-per-line": "warn",
            "react/jsx-newline": "warn",
            "react/jsx-no-bind": "warn",
            "react/jsx-no-comment-textnodes": "warn",
            "react/jsx-no-constructed-context-values": "error",
            "react/jsx-no-duplicate-props": "error",
            "react/jsx-no-leaked-render": "warn",
            "react/jsx-no-literals": "warn",
            "react/jsx-no-script-url": "error",
            "react/jsx-no-target-blank": "error",
            "react/jsx-no-undef": "error",
            "react/jsx-no-useless-fragment": "warn",
            "react/jsx-pascal-case": "warn",
            "react/jsx-props-no-multi-spaces": "warn",
            "react/jsx-props-no-spread-multi": "warn",
            "react/jsx-props-no-spreading": "warn",
            "react/sort-default-props": "warn",
            "react/jsx-sort-props": "warn",
            "react/jsx-uses-react": "warn",
            "react/jsx-uses-vars": "warn",
            "react/jsx-wrap-multilines": "warn",
            "react/no-access-state-in-setstate": "error",
            "react/no-adjacent-inline-elements": "warn",
            "react/no-array-index-key": "warn",
            "react/no-arrow-function-lifecycle": "error",
            "react/no-children-prop": "error",
            "react/no-danger": "warn",
            "react/no-danger-with-children": "error",
            "react/no-deprecated": "error",
            "react/no-did-mount-set-state": "error",
            "react/no-did-update-set-state": "error",
            "react/no-direct-mutation-state": "error",
            "react/no-find-dom-node": "error",
            "react/no-invalid-html-attribute": "error",
            "react/no-is-mounted": "error",
            "react/no-multi-comp": "warn",
            "react/no-namespace": "warn",
            "react/no-object-type-as-default-prop": "warn",
            "react/no-redundant-should-component-update": "warn",
            "react/no-render-return-value": "error",
            "react/no-set-state": "warn",
            "react/no-string-refs": "error",
            "react/no-this-in-sfc": "error",
            "react/no-typos": "warn",
            "react/no-unescaped-entities": "warn",
            "react/no-unknown-property": "error",
            "react/no-unsafe": "error",
            "react/no-unstable-nested-components": "error",
            "react/no-unused-class-component-methods": "warn",
            "react/no-unused-prop-types": "warn",
            "react/no-unused-state": "warn",
            "react/no-will-update-set-state": "error",
            "react/prefer-es6-class": "warn",
            "react/prefer-exact-props": "warn",
            "react/prefer-read-only-props": "warn",
            "react/prefer-stateless-function": "warn",
            "react/prop-types": "error",
            "react/react-in-jsx-scope": "error",
            "react/require-default-props": "warn",
            "react/require-optimization": "warn",
            "react/require-render-return": "error",
            "react/self-closing-comp": "warn",
            "react/sort-comp": "warn",
            "react/sort-default-props": "warn",
            "react/sort-prop-types": "warn",
            "react/state-in-constructor": "warn",
            "react/static-property-placement": "warn",
            "react/style-prop-object": "warn",
            "react/void-dom-elements-no-children": "error",
        },
        stylistic: {
            "stylistic/array-bracket-newline": ["warn", "consistent"],
            "stylistic/array-bracket-spacing": ["warn", "never"],
            "stylistic/array-element-newline": ["warn", "consistent"],
            "stylistic/arrow-parens": ["warn", "as-needed"],
            "stylistic/arrow-spacing": ["warn", { before: true, after: true }],
            "stylistic/block-spacing": ["warn", "always"],
            "stylistic/brace-style": ["warn", "1tbs", { allowSingleLine: true }],
            "stylistic/comma-dangle": ["warn", "always-multiline"],
            "stylistic/comma-spacing": ["warn", { before: false, after: true }],
            "stylistic/comma-style": ["warn", "last"],
            "stylistic/computed-property-spacing": ["warn", "never"],
            "stylistic/curly-newline": ["warn"],
            "stylistic/dot-location": ["warn", "property"],
            "stylistic/eol-last": ["warn", "always"],
            "stylistic/function-call-argument-newline": ["warn", "consistent"],
            "stylistic/function-call-spacing": ["warn"],
            "stylistic/function-paren-newline": ["warn", "consistent"],
            "stylistic/generator-star-spacing": ["warn", { before: false, after: true }],
            "stylistic/implicit-arrow-linebreak": ["warn", "beside"],
            "stylistic/indent": ["warn", 4, {
                SwitchCase: 1,
                VariableDeclarator: "first",
                outerIIFEBody: 1,
                MemberExpression: 1,
                FunctionDeclaration: { parameters: "first" },
                FunctionExpression: { parameters: "first" },
                CallExpression: { arguments: "first" },
                ArrayExpression: 1,
                ObjectExpression: 1,
                ImportDeclaration: 1,
                flatTernaryExpressions: false,
                offsetTernaryExpressions: true,
            }],
            "stylistic/indent-binary-ops": ["warn", 4],
            "stylistic/key-spacing": ["warn", { beforeColon: false, afterColon: true }],
            "stylistic/keyword-spacing": ["warn", { before: true, after: true }],
            "stylistic/line-comment-position": "off",
            "stylistic/linebreak-style": ["warn", "unix"],
            "stylistic/lines-around-comment": ["warn", {
                beforeBlockComment: true,
                afterBlockComment: false,
                beforeLineComment: false,
                afterLineComment: false,
                allowArrayStart: true,
                allowArrayEnd: true,
                allowBlockStart: true,
                allowBlockEnd: true,
                allowClassStart: true,
                allowClassEnd: true,
                allowEnumStart: true,
                allowEnumEnd: true,
                allowInterfaceStart: true,
                allowInterfaceEnd: true,
                allowModuleStart: true,
                allowModuleEnd: true,
                allowObjectStart: true,
                allowObjectEnd: true,
                allowTypeStart: true,
                allowTypeEnd: true,
            }],
            "stylistic/lines-between-class-members": ["warn", "always"],
            "stylistic/max-len": ["warn", {
                code: 200,
                tabWidth: 4,
                comments: 200,
                ignoreUrls: true,
                ignoreStrings: true,
                ignoreTemplateLiterals: true,
                ignoreRegExpLiterals: true,
            }],
            "stylistic/max-statements-per-line": ["warn", { max: 1 }],
            "stylistic/member-delimiter-style": ["warn", {
                multiline: {
                    delimiter: "comma",
                    requireLast: true,
                },
                singleline: {
                    delimiter: "comma",
                    requireLast: false,
                }
            }],
            "stylistic/multiline-comment-style": ["warn", "separate-lines", { checkJSDoc: false }],
            "stylistic/multiline-ternary": ["warn", "always-multiline"],
            "stylistic/new-parens": "warn",
            "stylistic/newline-per-chained-call": ["warn", { ignoreChainWithDepth: 3 }],
            "stylistic/no-confusing-arrow": ["warn", { allowParens: true }],
            "stylistic/no-extra-parens": ["warn", "all", { nestedBinaryExpressions: false }],
            "stylistic/no-extra-semi": "warn",
            "stylistic/no-floating-decimal": "warn",
            "stylistic/no-mixed-operators": "warn",
            "stylistic/no-mixed-spaces-and-tabs": "error",
            "stylistic/no-multi-spaces": "warn",
            "stylistic/no-multiple-empty-lines": ["warn", { max: 1, maxEOF: 0 }],
            "stylistic/no-tabs": "error",
            "stylistic/no-trailing-spaces": "warn",
            "stylistic/no-whitespace-before-property": "warn",
            "stylistic/nonblock-statement-body-position": ["warn", "beside"],
            "stylistic/object-curly-newline": ["warn"],
            "stylistic/object-curly-spacing": ["warn", "always"],
            "stylistic/object-property-newline": ["warn", { allowAllPropertiesOnSameLine: true }],
            "stylistic/one-var-declaration-per-line": ["warn", "initializations"],
            "stylistic/operator-linebreak": ["warn", "after", { "overrides": { "?": "before", ":": "before" } }],
            "stylistic/padded-blocks": ["warn", "never"],
            "padding-line-between-statements": [
                "warn",
                { blankLine: "always", prev: ["block", "block-like"], next: "return" },
                { blankLine: "always", prev: ["const", "let", "var"], next: "*" },
                { blankLine: "any", prev: ["const", "let", "var"], next: ["const", "let", "var"] }
            ],
            "stylistic/quote-props": ["warn", "consistent-as-needed"],
            "stylistic/quotes": ["warn", "double", { avoidEscape: false }],
            "stylistic/rest-spread-spacing": ["warn", "never"],
            "stylistic/semi": ["warn", "always"],
            "stylistic/semi-spacing": ["warn", { before: false, after: true }],
            "stylistic/semi-style": ["warn", "last"],
            "stylistic/space-before-blocks": "warn",
            "stylistic/space-before-function-paren": ["warn", {
                anonymous: "always",
                named: "never",
                asyncArrow: "always",
            }],
            "stylistic/space-in-parens": ["warn", "never"],
            "stylistic/space-infix-ops": "warn",
            "stylistic/space-unary-ops": ["warn", {
                words: true,
                nonwords: false,
            }],
            "stylistic/spaced-comment": ["warn", "always", {
                line: {
                    markers: ["/"],
                    exceptions: ["-", "+"],
                },
                block: {
                    markers: ["!"],
                    exceptions: ["*"],
                    balanced: true,
                }
            }],
            "stylistic/switch-colon-spacing": ["warn", { after: true, before: false }],
            "stylistic/template-curly-spacing": ["warn", "never"],
            "stylistic/template-tag-spacing": ["warn", "never"],
            "stylistic/type-annotation-spacing": "warn",
            "stylistic/type-generic-spacing": "warn",
            "stylistic/type-named-tuple-spacing": "warn",
            "stylistic/wrap-iife": ["warn", "inside"],
            "stylistic/wrap-regex": "warn",
            "stylistic/yield-star-spacing": ["warn", { before: false, after: true }],
        },
        typescript: {
            "typescript/adjacent-overload-signatures": "warn",
            "typescript/array-type": ["warn", { "default": "array-simple" }],
            "typescript/await-thenable": "error",
            "typescript/ban-ts-comment": "off",
            "typescript/ban-tslint-comment": "off",
            "typescript/class-literal-property-style": "off",
            "typescript/class-methods-use-this": "off",
            "typescript/consistent-generic-constructors": ["warn", "constructor"],
            "typescript/consistent-indexed-object-style": ["warn", "record"],
            "typescript/consistent-return": "off",
            "typescript/consistent-type-assertions": ["warn", { assertionStyle: "as", objectLiteralTypeAssertions: "never" }],
            "typescript/consistent-type-definitions": ["warn", "interface"],
            "typescript/consistent-type-exports": "warn",
            "typescript/consistent-type-imports": ["warn", { prefer: "type-imports", fixStyle: "inline-type-imports" }],
            "typescript/default-param-last": "error",
            "typescript/dot-notation": ["warn", { allowPrivateClassPropertyAccess: true }],
            "typescript/explicit-function-return-type": ["warn", { allowExpressions: true, allowTypedFunctionExpressions: true, allowHigherOrderFunctions: true }],
            "typescript/explicit-member-accessibility": ["warn", { accessibility: "explicit", overrides: { constructors: "no-public" } }],
            "typescript/explicit-module-boundary-types": ["warn", { allowArgumentsExplicitlyTypedAsAny: true, allowDirectConstAssertionInArrowFunctions: true }],
            "typescript/init-declarations": "off",
            "typescript/max-params": ["warn", { max: 5 }],
            "typescript/member-ordering": "warn",
            "typescript/method-signature-style": ["warn", "property"],
            "typescript/naming-convention": [
                "warn",
                {
                    selector: "default",
                    format: ["camelCase"],
                },
                {
                    selector: "variable",
                    format: ["camelCase", "UPPER_CASE"],
                },
                {
                    selector: "parameter",
                    format: ["camelCase", "PascalCase"],
                    leadingUnderscore: "forbid",
                },
                {
                    selector: "memberLike",
                    modifiers: ["private"],
                    format: ["camelCase"],
                    leadingUnderscore: "forbid",
                },
                {
                    selector: "typeLike",
                    format: ["PascalCase"],
                },
                {
                    selector: "enumMember",
                    format: ["UPPER_CASE"],
                },
                {
                    selector: "import",
                    format: ["camelCase", "PascalCase"],
                },
            ],
            "typescript/no-array-constructor": "error",
            "typescript/no-array-delete": "error",
            "typescript/no-base-to-string": "warn",
            "typescript/no-confusing-non-null-assertion": "warn",
            "typescript/no-confusing-void-expression": "warn",
            "typescript/no-deprecated": "warn",
            "typescript/no-dupe-class-members": "error",
            "typescript/no-duplicate-enum-values": "warn",
            "typescript/no-duplicate-type-constituents": "warn",
            "typescript/no-dynamic-delete": "warn",
            "typescript/no-empty-function": ["warn", { "allow": ["arrowFunctions", "private-constructors", "protected-constructors"] }],
            "typescript/no-empty-interface": "off",
            "typescript/no-empty-object-type": "warn",
            "typescript/no-explicit-any": "warn",
            "typescript/no-extra-non-null-assertion": "warn",
            "typescript/no-extraneous-class": "warn",
            "typescript/no-floating-promises": "error",
            "typescript/no-for-in-array": "error",
            "typescript/no-implied-eval": "error",
            "typescript/no-import-type-side-effects": "warn",
            "typescript/no-inferrable-types": ["warn", { ignoreParameters: true, ignoreProperties: true }],
            "typescript/no-invalid-this": "error",
            "typescript/no-invalid-void-type": ["warn", { allowAsThisParameter: true }],
            "typescript/no-loop-func": "error",
            "typescript/no-loss-of-precision": "warn",
            "typescript/no-magic-numbers": ["off", { ignoreArrayIndexes: true, ignoreDefaultValues: true, ignoreClassFieldInitialValues: true, ignore: [0, 1] }],
            "typescript/no-meaningless-void-operator": "warn",
            "typescript/no-misused-new": "error",
            "typescript/no-misused-promises": "error",
            "typescript/no-misused-spread": "error",
            "typescript/no-mixed-enums": "error",
            "typescript/no-namespace": "error",
            "typescript/no-non-null-asserted-nullish-coalescing": "error",
            "typescript/no-non-null-asserted-optional-chain": "error",
            "typescript/no-non-null-assertion": "error",
            "typescript/no-redeclare": "error",
            "typescript/no-redundant-type-constituents": "warn",
            "typescript/no-restricted-imports": "off",
            "typescript/no-restricted-types": "off",
            "typescript/no-shadow": "error",
            "typescript/no-this-alias": "off",
            "typescript/no-type-alias": "off",
            "typescript/no-unnecessary-boolean-literal-compare": "warn",
            "typescript/no-unnecessary-condition": "warn",
            "typescript/no-unnecessary-parameter-property-assignment": "warn",
            "typescript/no-unnecessary-qualifier": "warn",
            "typescript/no-unnecessary-template-expression": "warn",
            "typescript/no-unnecessary-type-arguments": "warn",
            "typescript/no-unnecessary-type-assertion": "warn",
            "typescript/no-unnecessary-type-constraint": "warn",
            "typescript/no-unnecessary-type-conversion": "warn",
            "typescript/no-unnecessary-type-parameters": "off",
            "typescript/no-unsafe-argument": "error",
            "typescript/no-unsafe-assignment": "error",
            "typescript/no-unsafe-call": "error",
            "typescript/no-unsafe-declaration-merging": "error",
            "typescript/no-unsafe-enum-comparison": "error",
            "typescript/no-unsafe-function-type": "error",
            "typescript/no-unsafe-member-access": "error",
            "typescript/no-unsafe-return": "error",
            "typescript/no-unsafe-type-assertion": "off",
            "typescript/no-unsafe-unary-minus": "error",
            "typescript/no-unused-expressions": "warn",
            "typescript/no-unused-vars": ["warn", {
                "argsIgnorePattern": "^_",
                "caughtErrors": "all",
                "caughtErrorsIgnorePattern": "^_",
                "destructuredArrayIgnorePattern": "^_",
                "varsIgnorePattern": "^_",
            }],
            "typescript/no-use-before-define": ["error", { "functions": false, "classes": false, "variables": true }],
            "typescript/no-useless-constructor": "error",
            "typescript/no-useless-empty-export": "warn",
            "typescript/no-var-requires": "off",
            "typescript/no-wrapper-object-types": "warn",
            "typescript/non-nullable-type-assertion-style": "warn",
            "typescript/only-throw-error": "error",
            "typescript/parameter-properties": ["warn", { allow: ["private", "protected", "public"] }],
            "typescript/prefer-as-const": "off",
            "typescript/prefer-destructuring": "off",
            "typescript/prefer-enum-initializers": "warn",
            "typescript/prefer-find": "off",
            "typescript/prefer-for-of": "warn",
            "typescript/prefer-function-type": "warn",
            "typescript/prefer-includes": "warn",
            "typescript/prefer-literal-enum-member": "off",
            "typescript/prefer-namespace-keyword": "off",
            "typescript/prefer-nullish-coalescing": "warn",
            "typescript/prefer-optional-chain": "warn",
            "typescript/prefer-promise-reject-errors": ["error", { "allowEmptyReject": true }],
            "typescript/prefer-readonly": "off",
            "typescript/prefer-readonly-parameter-types": "off",
            "typescript/prefer-reduce-type-parameter": "warn",
            "typescript/prefer-regexp-exec": "warn",
            "typescript/prefer-return-this-type": "warn",
            "typescript/prefer-string-starts-ends-with": "warn",
            "typescript/prefer-ts-expect-error": "off",
            "typescript/promise-function-async": "error",
            "typescript/related-getter-setter-pairs": "warn",
            "typescript/require-array-sort-compare": "warn",
            "typescript/require-await": "error",
            "typescript/restrict-plus-operands": "error",
            "typescript/restrict-template-expressions": "warn",
            "typescript/return-await": "error",
            "typescript/sort-type-constituents": "off",
            "typescript/strict-boolean-expressions": "error",
            "typescript/switch-exhaustiveness-check": "off",
            "typescript/triple-slash-reference": "error",
            "typescript/typedef": "off",
            "typescript/unbound-method": "error",
            "typescript/unified-signatures": "off",
            "typescript/use-unknown-in-catch-callback-variable": "off",
        },
    }
}
