services:
  prometheus:
    image: prom/prometheus:latest
    container_name: trade2_prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - trade2_prometheus_data:/prometheus
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: trade2_loki
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/loki.yml
    volumes:
      - ./loki/loki.yml:/etc/loki/loki.yml
      - trade2_loki_data:/loki
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: trade2_grafana
    volumes:
      - trade2_grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_ADMIN_PASSWORD:-admin}
      GF_SERVER_ROOT_URL: https://trade2-monitoring-8vjke2-41ab39-157-90-114-60.traefik.me
      GF_SERVER_SERVE_FROM_SUB_PATH: 'false'
    depends_on:
      - prometheus
      - loki
    restart: unless-stopped

volumes:
  trade2_prometheus_data:
  trade2_loki_data:
  trade2_grafana_data:
