services:
  nestjs:
    build:
      context: .
      target: production
    container_name: trade2_nestjs
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_NAME: ${POSTGRES_NAME}
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}
      LOKI_URL: http://loki:3100
    depends_on:
      - postgres
      - minio
      - loki
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: trade2_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - trade2_minio_data:/data

  postgres:
    image: postgres:15
    container_name: trade2_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    volumes:
      - trade2_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: trade2_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - trade2_pgadmin_data:/var/lib/pgadmin
      - ./pgadmin.json:/pgadmin4/servers.json:ro
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: trade2_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitor/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - trade2_prometheus_data:/prometheus
    restart: unless-stopped

  loki:
    image: grafana/loki:2.9.8
    container_name: trade2_loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yml
    volumes:
      - ./monitor/loki/loki.yml:/etc/loki/loki.yml
      - trade2_loki_data:/loki
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.4.0
    container_name: trade2_grafana
    ports:
      - "3000:3000"
    volumes:
      - trade2_grafana_data:/var/lib/grafana
      - ./monitor/grafana/provisioning:/etc/grafana/provisioning
      - ./monitor/grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped

volumes:
  trade2_minio_data:
  trade2_postgres_data:
  trade2_pgadmin_data:
  trade2_loki_data:
  trade2_prometheus_data:
  trade2_grafana_data:
